### ISSUE TITLE
Steam slow speed in the evening

### ISSUE THREAD

**Issue by Momper14** [steamcache/monolithic#11]
### Describe the issue you are having
First, sorry for my bad English.

I’m testing the cache monolith. My problem is, the Steam speed slows down dramatically in the evening. I tested it at 10:00 (UTC+1) and get my normal 5 MB/s but in the evening (18:00 +) it varies between 2 MB/s and 500 KB/s. Without the monolith it’s still 5 MB/s. Tested it with Origin too but no problem here.
Same problem yesterday. Same problem with generic or the original Steamcache.

My hardware isn’t maxed out at any point and after its cached I get up to 100 MB/s from the Server (CPU Limited).

Any idea?

Edit: Tested it with Battle.net and Uplay. Also, no problem.

### How are you running the container(s)?
```
docker-compose.yml:

version: '3'
services:
  cache:
    container_name: cache
    hostname: cache
    image: steamcache/monolithic:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - cache:/data/cache/
      - logs:/data/logs/
      - cachedomains:/data/cachedomains/
      - www:/var/www/
    networks:
      nginx:
    environment:
      CACHE_MEM_SIZE: 4000m
      CACHE_DISK_SIZE: 3500g

volumes:
  cache:
    external: true
  logs:
  cachedomains:
  www:

networks:
  nginx:
    external: true
```

### DNS Configuration
```
Running a Pi-Hole with the dnsmasq made files from uklans/cache-domains
```
### Output of container(s)
```
[access.log](https://github.com/steamcache/monolithic/files/2866258/access.log)
[error.log](https://github.com/steamcache/monolithic/files/2866260/error.log)

Tell me if u need anything more and I will try to give it to you.
```
